### ISSUE TITLE
Questionable clean architecture implementation

### ISSUE THREAD

**Issue by md-redwan-hossain** [yanpitangui/dotnet-api-boilerplate#280]
**Is your feature request related to a problem? Please describe.**
Why EntityFramework is being added in the application layer? It must be in the infrastructure layer. application should not be concerned with your underlying database. Even `DatabaseFacade` is present in `Microsoft.EntityFrameworkCore.Infrastructure` namespace and you are using it in application layer.
```cs
using Boilerplate.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Boilerplate.Application.Common;

public interface IContext : IAsyncDisposable, IDisposable
{
    public DatabaseFacade Database { get; }
    
    public DbSet<Hero> Heroes { get; }
    
    public Task<int> SaveChangesAsync(CancellationToken cancellationToken = default);
}
```

**Describe alternatives you've considered**
Move them to infrastructure, use repository and unit of work pattern.

**Comment by md-redwan-hossain** [comment]
Yes vertical slicing will be a good choice. However, you can still use the implementation of EF's Repository pattern by utilizing generic repository, doing so, you don't need to drag EF in your application layer and code repetitions will be minimized. [Here is an implementation](https://gist.github.com/md-redwan-hossain/319001ebcbd1bceb8dc66b6cf6c4b138)

**Comment by yanpitangui** [comment]
Yes, I know I can do it that way. As I said, that was how it was [before I decided to remove it](https://github.com/yanpitangui/dotnet-api-boilerplate/commit/47980682f619991f4ceab9b92298249f28ebea56). The repository pattern is not the only way to reduce code repetitions. 
If everything I'm doing is using EF behind the scenes, "tainting" my application layer is just simplifying things.
Hopefully in the near future I will be able to take another round in the modernization of this project, and get away completely from "clean arch".
