### ISSUE TITLE
[FEATURE] Run api in IIS

### ISSUE THREAD

**Issue by longhus** [yanpitangui/dotnet-api-boilerplate#86]
How to run it on IIS server not console ?

**Comment by yanpitangui** [comment]
Do you mean to run locally? If that's your question, just select in visual studio your preferred running config:
![image](https://user-images.githubusercontent.com/15661613/225911736-26560585-ef5f-4ab4-8235-0e56c5b64b56.png)

If you are asking for deployment information, this is the documentation from Microsoft itself: https://learn.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-7.0&tabs=visual-studio
